# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'NewsReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsReader
  pod 'SnapKit', '~> 5.6'
  pod 'SDWebImage/Core', :modular_headers => true
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
  
  target 'NewsReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
